// eslint-disable-next-line @typescript-eslint/no-explicit-any
type IpcCallback<T = any> = (value: T) => void;
type UnsubscribeFn = () => void;

interface ElectronAPI {
  platform: string;
  isPackaged: boolean;
  isDeveloperMode: boolean;
  getVersion: () => Promise<string>;

  minimize: () => void;
  maximize: () => void;
  close: () => void;
  openFileDialog: (options?: any) => Promise<any>;
  showSaveDialog: (options?: any) => Promise<any>;
  getSettings: () => Promise<any>;
  saveSettings: (settings: any) => Promise<any>;
  login: () => Promise<any>;
  logout: () => Promise<any>;
  validateSession: () => Promise<any>;
  getProfile: () => Promise<any>;
  getAccounts: () => Promise<any>;
  switchAccount: (uuid: string) => Promise<any>;
  removeAccount: (uuid: string) => Promise<any>;
  selectBackgroundMedia: () => Promise<any>;
  deleteBackgroundMedia: (path: string) => Promise<any>;
  selectCustomFont: () => Promise<any>;
  deleteCustomFont: (fontId: string) => Promise<any>;
  getCustomPresets: () => Promise<any>;
  saveCustomPreset: (preset: any) => Promise<any>;
  deleteCustomPreset: (handle: string) => Promise<any>;
  exportCustomPreset: (preset: any) => Promise<any>;
  importCustomPreset: () => Promise<any>;
  installThemeFromMarketplace: (url: string) => Promise<any>;

  softReset: () => Promise<any>;
  factoryReset: () => Promise<any>;

  openInstanceFolder: (name: string) => Promise<any>;
  openResourcePacksFolder: (instanceName: string) => Promise<any>;
  installResourcePack: (instanceName: string, filePath: string) => Promise<any>;
  toggleResourcePack: (instanceName: string, packFileName: string) => Promise<any>;
  downloadResourcePack: (instanceName: string, url: string) => Promise<any>;
  deleteResourcePack: (instanceName: string, packFileName: string) => Promise<any>;
  getMods: (instanceName: string) => Promise<any>;
  getResourcePacks: (instanceName: string) => Promise<any>;
  getShaders: (instanceName: string) => Promise<any>;
  toggleMod: (instanceName: string, fileName: string) => Promise<any>;
  deleteMod: (instanceName: string, fileName: string, type?: string) => Promise<any>;
  getWorlds: (instanceName: string) => Promise<any>;
  openWorldFolder: (instanceName: string, folderName: string) => Promise<any>;
  backupWorld: (instanceName: string, folderName: string, forceCloud?: boolean) => Promise<any>;
  deleteWorld: (instanceName: string, folderName: string) => Promise<any>;
  exportWorld: (instanceName: string, folderName: string) => Promise<any>;
  getLogFiles: (instanceName: string) => Promise<any>;
  getLog: (instanceName: string, filename: string) => Promise<any>;
  launchGame: (instanceName: string, quickPlay?: any) => Promise<any>;
  getLiveLogs: (instanceName: string) => Promise<any>;
  killGame: (instanceName: string) => Promise<any>;
  abortLaunch: (instanceName: string) => Promise<any>;
  createInstance: (name: string, version: string, loader: string, icon: string | null, loaderVersion?: string | null, options?: any) => Promise<any>;
  updateInstance: (name: string, config: any) => Promise<any>;
  updateInstanceConfig: (name: string, config: any) => Promise<any>;
  migrateInstance: (name: string, config: any) => Promise<any>;
  reinstallInstance: (name: string, type?: string) => Promise<any>;
  deleteInstance: (name: string) => Promise<any>;
  renameInstance: (oldName: string, newName: string) => Promise<any>;
  duplicateInstance: (name: string) => Promise<any>;
  exportInstance: (name: string) => Promise<any>;
  exportVoidrixModpack: (name: string) => Promise<any>;
  exportMrpack: (name: string) => Promise<any>;
  exportInstanceZip: (name: string) => Promise<any>;
  importVoidrixModpack: () => Promise<any>;
  importVoidrixModpackStrict: () => Promise<any>;
  importVoidrixModpackFile: (filePath: string) => Promise<any>;
  importInstance: () => Promise<any>;
  importMrPack: () => Promise<any>;
  importFile: () => Promise<any>;
  ping: () => Promise<any>;
  restartApp: () => Promise<any>;
  getInstances: () => Promise<any>;
  installModpack: (url: string, name: string, iconUrl?: string) => Promise<any>;
  searchModrinth: (query: string, facets?: any, options?: any) => Promise<any>;
  modrinthSearch: (query: string, facets?: any, options?: any) => Promise<any>;
  installMod: (data: any) => Promise<any>;
  modrinthInstall: (data: any) => Promise<any>;
  installLocalMod: (instanceName: string, filePath: string, type?: string) => Promise<any>;
  getModVersions: (projectId: string, loaders?: any, gameVersions?: any, fallbackCurseForgeProjectId?: string | null) => Promise<any>;
  getModrinthProject: (projectId: string) => Promise<any>;
  resolveDependencies: (versionId: string, loaders?: any, gameVersions?: any) => Promise<any>;
  checkUpdates: (instanceName: string, files?: any) => Promise<any>;
  updateFile: (data: any) => Promise<any>;
  getVanillaVersions: () => Promise<any>;
  getLoaderVersions: (loader: string, mcVersion: string) => Promise<any>;
  getSupportedGameVersions: (loader: string) => Promise<any>;
  getLoaders: (mcVersion?: string, loaderType?: string) => Promise<any>;
  getNews: () => Promise<any>;
  installJava: (version: string) => Promise<any>;
  getJavaRuntimes: () => Promise<any>;
  deleteJavaRuntime: (path: string) => Promise<any>;
  openJavaFolder: () => Promise<any>;
  openExternal: (url: string) => Promise<any>;
  runExternalFile: (filePath: string) => Promise<any>;
  exportModpackAsCode: (data: any) => Promise<any>;
  importModpackFromCode: (code: string) => Promise<any>;
  getModpackCodes: () => Promise<any>;
  deleteModpackCode: (code: string) => Promise<any>;
  installSharedContent: (instanceName: string, modpackData: any) => Promise<any>;
  getCurrentSkin: (token: string) => Promise<any>;
  uploadSkin: (token: string, skinPath: string, variant: string) => Promise<any>;
  uploadSkinFromUrl: (token: string, skinUrl: string, variant: string) => Promise<any>;
  setCape: (token: string, capeId: string) => Promise<any>;
  saveLocalSkin: (filePath?: string | { source: string; value: string; name?: string; model?: string; outputPath?: string }) => Promise<any>;
  saveLocalSkinFromUrl: (skinUrl: string) => Promise<any>;
  saveLocalSkinFromUsername: (username: string) => Promise<any>;
  getLocalSkins: () => Promise<any>;
  exportLocalSkin: (id: string) => Promise<any>;
  deleteLocalSkin: (id: string) => Promise<any>;
  renameLocalSkin: (id: string, newName: string) => Promise<any>;

  onUpdateAvailable: (callback: IpcCallback) => UnsubscribeFn;
  onUpdateNotAvailable: (callback: IpcCallback) => UnsubscribeFn;
  onUpdateProgress: (callback: IpcCallback) => UnsubscribeFn;
  onUpdateDownloaded: (callback: IpcCallback) => UnsubscribeFn;
  onUpdateError: (callback: IpcCallback) => UnsubscribeFn;
  restartAndInstall: () => void;
  onLaunchProgress: (callback: IpcCallback) => UnsubscribeFn;
  onLaunchLog: (callback: IpcCallback) => UnsubscribeFn;
  onInstanceStatus: (callback: IpcCallback) => UnsubscribeFn;
  onInstallProgress: (callback: IpcCallback) => UnsubscribeFn;
  onLoginSuccess: (callback: IpcCallback) => UnsubscribeFn;
  onThemeUpdated: (callback: IpcCallback) => UnsubscribeFn;
  onSettingsUpdated: (callback: IpcCallback) => UnsubscribeFn;
  onJavaProgress: (callback: IpcCallback) => UnsubscribeFn;
  onWindowStateChange: (callback: IpcCallback) => UnsubscribeFn;

  selectFolder: () => Promise<any>;


  getExtensions: () => Promise<any>;
  installExtension: (sourcePath: string) => Promise<any>;
  removeExtension: (id: string) => Promise<any>;
  toggleExtension: (id: string, enabled: boolean) => Promise<any>;
  onExtensionFile: (callback: IpcCallback) => UnsubscribeFn;
  getActiveProcesses: () => Promise<any>;
  getProcessStats: (pid: number) => Promise<any>;

  invokeExtension: (extId: string, channel: string, ...args: any[]) => Promise<any>;
  onExtensionMessage: (extId: string, channel: string, callback: (...args: any[]) => void) => UnsubscribeFn;
  fetchMarketplace: () => Promise<any>;

  cloudLogin: (providerId: string) => Promise<any>;
  cloudLogout: (providerId: string) => Promise<any>;
  cloudGetStatus: () => Promise<any>;
  cloudListBackups: (providerId: string, instanceName?: string) => Promise<any>;
  cloudUpload: (providerId: string, filePath: string, instanceName?: string) => Promise<any>;
  cloudDownload: (providerId: string, fileId: string, targetPath?: string) => Promise<any>;
  backupInstance: (instanceName: string) => Promise<any>;
  listLocalBackups: (instanceName: string) => Promise<any>;
  getBackupsDir: (instanceName: string) => Promise<any>;
  restoreLocalBackup: (instanceName: string, backupFileName: string) => Promise<any>;
  removeFile: (filePath: string) => Promise<any>;

  checkForUpdates: () => Promise<any>;
  downloadUpdate: (url: string, name: string) => Promise<any>;
  installUpdate: (path: string) => Promise<any>;
  setTestVersion: (version: string) => Promise<any>;
  onUpdaterProgress: (callback: IpcCallback) => UnsubscribeFn;
  onCrashReport: (callback: IpcCallback) => UnsubscribeFn;
}